import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#2f312d",
        "on-primary-fixed": "#1c1b1c",
        "tertiary-fixed-dim": "#f4bb8d",
        "secondary-container": "#484a45",
        "outline": "#919094",
        "on-tertiary": "#4a2806",
        "inverse-surface": "#e4e2e4",
        "on-secondary-container": "#b8b9b3",
        "error": "#ffb4ab",
        "on-surface": "#e4e2e4",
        "tertiary-fixed": "#ffdcc2",
        "surface-container-lowest": "#0e0e10",
        "on-surface-variant": "#c7c6ca",
        "surface-container-low": "#1b1b1d",
        "surface-container-highest": "#353437",
        "on-tertiary-fixed-variant": "#653e1a",
        "on-background": "#e4e2e4",
        "on-tertiary-fixed": "#2e1500",
        "tertiary-container": "#1c0b00",
        "inverse-primary": "#5f5e5f",
        "surface-dim": "#131315",
        "primary": "#c8c6c7",
        "on-error": "#690005",
        "secondary-fixed-dim": "#c6c7c0",
        "inverse-on-surface": "#303032",
        "background": "#131315",
        "outline-variant": "#46464a",
        "on-primary": "#313031",
        "error-container": "#93000a",
        "surface-container-high": "#2a2a2c",
        "secondary-fixed": "#e3e3dc",
        "tertiary": "#f4bb8d",
        "on-primary-container": "#7d7b7c",
        "primary-fixed-dim": "#c8c6c7",
        "on-tertiary-container": "#a17249",
        "surface-container": "#1f1f21",
        "surface": "#131315",
        "surface-bright": "#39393b",
        "secondary": "#c6c7c0",
        "primary-fixed": "#e5e2e3",
        "on-secondary-fixed-variant": "#464743",
        "on-secondary-fixed": "#1a1c18",
        "surface-variant": "#353437",
        "on-primary-fixed-variant": "#474647",
        "primary-container": "#0f0f10",
        "on-error-container": "#ffdad6",
        "surface-tint": "#c8c6c7"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        gutter: "24px",
        "margin-desktop": "48px",
        xl: "64px",
        "margin-mobile": "16px",
        lg: "40px",
        base: "4px",
        xs: "8px",
        md: "24px",
        sm: "16px",
        "window-padding": "32px"
      },
      fontFamily: {
        "headline-xl": ["Hanken Grotesk"],
        "body-md": ["Source Serif 4"],
        "headline-md": ["Hanken Grotesk"],
        "label-md": ["Hanken Grotesk"],
        "body-lg": ["Source Serif 4"],
        "headline-lg": ["Hanken Grotesk"],
        "label-sm": ["Hanken Grotesk"],
        "eyebrow": ["Hanken Grotesk"],
        "display-xl": ["Hanken Grotesk"],
        "editorial-body": ["Source Serif 4"]
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "eyebrow": ["10px", { lineHeight: "16px", letterSpacing: "1.67px", fontWeight: "700" }],
        "display-xl": ["84px", { lineHeight: "90px", letterSpacing: "-0.02em", fontWeight: "900" }],
        "headline-lg-mobile": ["32px", { lineHeight: "38px", fontWeight: "700" }],
        "editorial-body": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      }
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
export default config;
